name: lint / rdoc

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/lint--rdoc.yaml
      - Gemfile.lock
      - Rakefile
      - lib/**/*
      - README.md
  pull_request:
    paths:
      - .github/workflows/lint--rdoc.yaml
      - Gemfile.lock
      - Rakefile
      - lib/**/*
      - README.md

permissions:
  contents: read

env:
  BUNDLE_ONLY: documentation

jobs:
  rdoc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: true
      - uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4 # v1.323.0
        with:
          bundler-cache: true
          cache-version: ${{ hashFiles('Gemfile.lock') }}
      - name: Generate API documentation
        run: bundle exec rake rdoc
